### ISSUE TITLE
Android : codename, device command is broken

### ISSUE THREAD

**Issue by RealAkito** [RaphielGang/Telegram-Paperplane#236]
**Describe the bug**
codename, device, and specs command is broken in Android module

**To Reproduce**
Use codename, device or specs command from Android module

**Expected behavior**
codename - Get codename from a brand and a device name
device - Get device info from codename
specs - Same usage as codename, but get the device specs instead

**Python Version**
Arch Linux Python 3.8.2

**Comment by RealAkito** [comment]
Informing the module author, @yshalsager regarding this.

**Comment by zakaryan2004** [comment]
The specs command doesn't seem to work properly too.

**Comment by RealAkito** [comment]
> The specs command doesn't seem to work properly too.

Thanks for confirming that. I have just realized it does not work as intended as well. Will edit the main post.

**Comment by zakaryan2004** [comment]
> > The specs command doesn't seem to work properly too.
> 
> Thanks for confirming that. I have just realized it does not work as intended as well. Will edit the main post.

It actually seems most of the problems come from the API which is used, it seems another API should be used. I haven't looked into this module at all, I can't say anything for sure. It should either be fixed or removed.

**Comment by RealAkito** [comment]
#240 have fixed this issue, I am closing.
