### ISSUE TITLE
[Pull Request] Help module as list

### ISSUE THREAD

**Issue by ghost** [RaphielGang/Telegram-Paperplane#251]
Current help module is like this right?: Admins, memes, and, other, stuff,
This type will be better i guess:
- Admins
- memes
- and
- other
- stuff

**Comment by raphielscape** [comment]
The modules are quite huge so making it a list will be a literal long message, except if we outputting it to a file instead of making it a message

**Comment by zakaryan2004** [comment]
Yeah, the message will be longer, but I actually think it'll look cleaner.

**Comment by Shiroikun** [comment]
> Yeah, the message will be longer, but I actually think it'll look cleaner.

to be hones and as far as i saw, all other userbots use this type of list

**Comment by AvinashReddy3108** [comment]
> Yeah, the message will be longer, but I actually think it'll look cleaner.

Yes, but do note that every newline in the help text adds 2 chars to the `len(event.message)`
*Just saying..*

**Comment by zakaryan2004** [comment]
> > Yeah, the message will be longer, but I actually think it'll look cleaner.
> 
> Yes, but do note that every newline in the help text adds 2 chars to the `len(event.message)`
> *Just saying..*

Yes, it will, but currently the ", " separator adds 2 characters too.

Also I doubt the message length will ever reach the limit.

**Comment by zakaryan2004** [comment]
This has been implemented.
