### ISSUE TITLE
po

### ISSUE THREAD

**Issue by Sara2002a** [RaphielGang/Telegram-Paperplane#276]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by Sara2002a** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

**Comment by Sara2002a** [comment]
J

**Comment by AvinashReddy3108** [comment]
Imagine choosing GitHub as a platform to spam SMH
